services:
  auth:
    build: .
    container_name: auth
    env_file:
      - ../.env
      - .env
    ports:
      - "8001:8000"
    depends_on:
      - auth_db
    volumes:
      - .:/app
    networks:
      - backend

  auth_db:
    image: postgres:15
    container_name: auth_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  auth_db_data: